Update action and remove test-submit since it needs the firebase emulator to be running

diff --git a/.github/actions/run-automation-tests/action.yml b/.github/actions/run-automation-tests/action.yml
--- a/.github/actions/run-automation-tests/action.yml
+++ b/.github/actions/run-automation-tests/action.yml
@@ -44,6 +44,17 @@ runs:
             exit 1
         fi
 
+    - name: Validate MAPS_API_KEY
+      env:
+        MAPS_API_KEY: ${{ inputs.google-maps-key }}
+      shell: bash
+      run: |
+        if [ -z "${MAPS_API_KEY}" ]; then
+          echo "MAPS_API_KEY is missing from GitHub secrets"
+          exit 1
+        fi
+        echo "MAPS_API_KEY is set"
+
     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
@@ -67,10 +78,8 @@ runs:
         path: |
           ~/.android/avd/*
           ~/.android/adb*
-        key: avd-35-google_apis_playstore-x86_64
-
-    - name: Setup Gradle
-      uses: gradle/gradle-build-action@v3
+        key: avd-35-google_apis_playstore-x86_64-v1
+        restore-keys: avd-35-google_apis_playstore-x86_64-
 
     - name: create AVD and generate snapshot for caching
       if: steps.avd-cache.outputs.cache-hit != 'true'
@@ -83,15 +92,10 @@ runs:
         emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back emulated -logcat '*:e'
         disable-animations: true
         script: |
-          adb shell settings put secure location_mode 3
-          adb shell settings put secure location_providers_allowed +gps
-          adb shell settings put secure location_providers_allowed +network
           echo "Generated AVD snapshot for caching."
 
     - name: Run tests
       uses: reactivecircus/android-emulator-runner@v2
-      env:
-        GOOGLE_MAPS_KEY: ${{ inputs.google-maps-key }}
       with:
         api-level: 35
         target: google_apis_playstore
@@ -100,15 +104,11 @@ runs:
         emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back emulated -logcat '*:e'
         disable-animations: true
         script: |
-          adb shell settings put secure location_mode 3
-          adb shell settings put secure location_providers_allowed +gps
-          adb shell settings put secure location_providers_allowed +network
-          adb emu geo fix -122.084 37.4220
-          sleep 2
-          echo "Generated AVD snapshot for caching."
+          echo "MAPS_API_KEY=${{ inputs.google-maps-key }}" > secrets.properties
+          ./gradlew :e2eTest:connectedLocalDebugAndroidTest --stacktrace
 
     - name: Upload test reports
-      if: always()
+      if: ${{ inputs.upload-artifacts == 'true' }}
       uses: actions/upload-artifact@v4
       with:
         name: test-reports
@@ -117,7 +117,7 @@ runs:
         if-no-files-found: warn
 
     - name: Upload test screenshots
-      if: always()
+      if: ${{ inputs.upload-artifacts == 'true' }}
       uses: actions/upload-artifact@v4
       with:
         name: test-screenshots
